USE master
GO

--
-- Initialize the UpdateProgramDB database.
--

CREATE DATABASE UpdateProgramDB ON PRIMARY (
    NAME       = N'UpdateProgramDB',
	FILENAME   = N'D:\Temp\UpdateProgram\db\UpdateProgramDB.mdf',
	SIZE       = 500MB,
	FILEGROWTH = 10MB
) LOG ON (
    NAME       = N'UpdateProgramDB_log',
	FILENAME   = N'D:\Temp\UpdateProgram\db\UpdateProgramDB_log.ldf',
	SIZE       = 500MB,
	FILEGROWTH = 10%
)
GO

ALTER DATABASE UpdateProgramDB SET COMPATIBILITY_LEVEL = 140
GO

ALTER DATABASE UpdateProgramDB set ANSI_NULL_DEFAULT OFF
GO

ALTER DATABASE UpdateProgramDB set ANSI_NULLS OFF
GO

ALTER DATABASE UpdateProgramDB set ANSI_PADDING OFF
GO

ALTER DATABASE UpdateProgramDB set ANSI_WARNINGS OFF
GO

ALTER DATABASE UpdateProgramDB set ARITHABORT OFF
GO

ALTER DATABASE UpdateProgramDB SET AUTO_CLOSE OFF
GO

ALTER DATABASE UpdateProgramDB SET AUTO_CREATE_STATISTICS ON
GO

ALTER DATABASE UpdateProgramDB SET AUTO_SHRINK OFF
GO

ALTER DATABASE UpdateProgramDB SET AUTO_UPDATE_STATISTICS ON
GO

ALTER DATABASE UpdateProgramDB SET CURSOR_CLOSE_ON_COMMIT OFF
GO

ALTER DATABASE UpdateProgramDB SET CURSOR_DEFAULT GLOBAL
GO

ALTER DATABASE UpdateProgramDB SET CONCAT_NULL_YIELDS_NULL OFF
GO

ALTER DATABASE UpdateProgramDB SET NUMERIC_ROUNDABORT OFF
GO

ALTER DATABASE UpdateProgramDB SET QUOTED_IDENTIFIER OFF
GO

ALTER DATABASE UpdateProgramDB SET RECURSIVE_TRIGGERS OFF
GO

ALTER DATABASE UpdateProgramDB SET DISABLE_BROKER
GO

ALTER DATABASE UpdateProgramDB SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO

ALTER DATABASE UpdateProgramDB SET DATE_CORRELATION_OPTIMIZATION OFF
GO

ALTER DATABASE UpdateProgramDB SET PARAMETERIZATION SIMPLE
GO

ALTER DATABASE UpdateProgramDB SET READ_WRITE
GO

ALTER DATABASE UpdateProgramDB SET RECOVERY FULL
GO

ALTER DATABASE UpdateProgramDB SET MULTI_USER
GO

ALTER DATABASE UpdateProgramDB SET PAGE_VERIFY CHECKSUM
GO

USE UpdateProgramDB
GO

IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default = 1 AND name = N'PRIMARY')
BEGIN
    ALTER DATABASE UpdateProgramDB MODIFY FILEGROUP [PRIMARY] DEFAULT
END
GO
